#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np

I0 = 0.2193839343955202736772

data = {}
with open('intg-smp.out') as equ:
    for line in equ:
        label, values = line.split(':')
        label = label.split('-')
        ngrad = int(label.pop())
        label = '-'.join(label)
        error = list(map(float, values.split()))[1]
        if label not in data:
            data[label] = [[ngrad, error]]
        else:
            data[label].append([ngrad, error])
data = {k: np.array(v) for (k, v) in data.items()}
for label, value in data.items():
    print(label, ':', sep='')
    print(value)
plt.title('integral errors of variant quadratures')
plt.xlabel('number of mesh points')
plt.ylabel(r'absolute error')
plt.yscale('log')
for label, values in data.items():
    plt.bar([str(int(v)) for v in values[:,0]], values[:,1], 0.4, label=label)
plt.legend()
plt.savefig(__file__ + '.pdf')
plt.show()
